apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-customer-api
spec:
  selector:
    matchLabels:
      app: elastic-customer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-customer-api
    spec:
      containers:
        - name: elastic-customer-api
          image: pasapples/elastic-customer-api:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-customer-api-lb
  labels:
    name: elastic-customer-api-lb
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: elastic-customer-api
  type: LoadBalancer